export const state = {
    _scMapCache: null,
    _hotFullRowCache: {},
    _marketMetricsTableAvailable: false,
    _auctionTableAvailable: false,
    _hotAuctionTableAvailable: false,
    _auctionWatchlistIndex: {},
    _hotWatchlistIndex: {},
    _jiwangDirtyDates: null,
    _auctionDirtyDates: null,
    _justPushedHotAuctionTimer: null,
    _justPushedHotAuction: false,
    _justPushedHotAuctionCounter: 0,
    _pushDebounceTimer: null,
    // §6：allData 仅为内存 CACHE（非真相源）——由各域 _xxxMemCache / Data getter 重建填充，不是五套真相之一。
    //     读取统一走 Data 层 getter（getStocksData()/getBiddingData()/getEtfData() 等）或各域 state._xxxMemCache，禁止当作真相源。
    allData: null,
    DATA_VERSION: null,
    _hotTrendsCache: {},
    _hotTrendsTableAvailable: false,
    _justPushedHotTrends: false,
    _hotNumcatDebugSnapshots: {},
    _auctionRealtimeTimer: null,
    _hotAuctionRealtimeTimer: null,
    _hotAuctionData: null,
    _syncState: null,
    _topicCache: null,
    _topicCacheBuilt: false,
    _justPushedAuction: false,
    _auctionWatchlistShadowIndex: {},
    _cloudTopicsCache: null,
    _jiwangPushTimers: {},
    _jiwangTableAvailable: false,
    _justPushedAuctionTimer: null,
    _justPushedBidding: false,
    _biddingPushInFlight: false,
    _justPushedJiwang: false,
    _pendingHotReload: false,
    _biddingTableAvailable: false,
    _rankTableAvailable: false,
    _multiTableAvailable: false,
    _hotspotTableAvailable: false,
    _patternTableAvailable: false,
    _duibanTableAvailable: false,
    _emotionTableAvailable: false,
    _emotionDataCache: null,
    _emotionExpandedRows: null,
    _emotionRealtimeChannel: null,
    _etfTableAvailable: false,
    _hotWatchlistShadowIndex: {},
    _auctionCodeMap: {},
    _hotAuctionTableAvailable2: false,
    _debugSnapshots: {},
    _pendingAuctionReload: false,
    _pendingJiwangReload: false,
    _auctionRealtimeChannel: null,
    _biddingDirtyDates: null,
    _biddingRealtimeChannel: null,
    _dailyHighlightsCache: {},
    _DBG_LOG_KEY: null,
    _DBG_VERBOSE: false,
    _dbgFlushTimer: null,
    _dbgFlushToSession: false,
    _dbgLogBuffer: [],
    _debugServerQueue: [],
    _debugServerTimer: null,
    _expandedAuctionStocksByGroup: {},
    _guardAssertDate: null,
    _guardStack: [],
    _highlightsChannel: null,
    _highlightsPushTimer: null,
    _highlightsTableAvailable: false,
    _histRowMapCache: {},
    _hotAuctionRealtimeChannel: null,
    _hotHighlightsCache: {},
    _hotHighlightsChannel: null,
    _hotHighlightsPushTimer: null,
    _hotHighlightsReloadTimer: null,
    _hotHighlightsTableAvailable: false,
    _hotTrendsRealtimeChannel: null,
    _hotTrendsReloadTimer: null,
    _jiwangRealtimeChannel: null,
    _justPushed: false,
    _justPushedAuctionCounter: 0,
    _justPushedHighlights: false,
    _justPushedHotHighlights: false,
    _lastPushedAuctionStatus: null,
    _logRenderAuctionCall: false,
    _marketMetricsHotRealtimeChannel: null,
    _marketMetricsRealtimeChannel: null,
    _migrateFromV41: null,
    _pendingHotRealtimeDates: {},
    _pendingRealtimeDates: {},
    _perfFrameScheduled: false,
    _perfLog: [],
    _perfPending: [],
    _realtimeChannel: null,
    _renderAuctionCallCount: 0,
    _renderAuctionLastLogTs: 0,
    _scheduleAuctionRealtimeReload: null,
    _scMapChannel: null,
    _sessionToken: null,
    _stockTopicsChannel: null,
    _supabaseClient: null,
    _topicCacheInvalidateCount: 0,
    _topicCacheLastInvalidateTs: 0,
    _topicCacheVersion: 0,
    HOT_MERGE_FIELDS: null,
    hotStockList: null,
    PASSWORD_HASH: null,
    SUPABASE_ANON_KEY: null,
    SUPABASE_URL: null,
    __auctionStoreFallback: null,
    _allDataLastRebuildAt: null, // §6：allData 缓存重建时间戳（仅观测用，非真相源）
    _allDataRebuildCount: 0, // §6：allData 缓存重建计数（仅观测用，非真相源）
    _auctionFullRowCache_DELETED: {},
    unlocked: false,
    _coreTopicsCloudLoaded: false,
    _coreTopicsPushingToCloud: false,
    _topicRankByDateCache: null,
    currentTrackEditId: null,
    _aiVisionTarget: null,
    _aiVisionImages: [],
    isStrengthSortEnabled: false,
    defaultCoreTopics: [
        { name: 'AI应用', synonyms: ['人工智能', 'AI', 'AI算力', '空间计算'] },
        { name: '机器人', synonyms: ['人形机器人', '工业机器人', '电机电控', '智元机器人', '机器视觉'] },
        { name: '商业航天', synonyms: ['航天', '卫星', '导航', '燃气轮机', '军工', '无人机', '航空发动机', '航天科技', '低空经济'] },
        { name: '液冷算力', synonyms: ['算力', '智算中心', '液冷', '服务器', '东数西算', '算力租赁'] },
        { name: '半导体', synonyms: ['芯片', '光刻机', '光刻胶', '洁净室', '存储', '光模块', 'RWA', 'GPU', '英伟达概念', '先进封装', '玻璃基板', '面板', '电子气体', 'OCS', 'MPO', 'CPO', '覆铜板', 'CCL', '电子树脂', '离子交换', 'OLED', '印制电路板', 'PCB', 'LED'] },
        { name: '新能源汽车', synonyms: ['新能源汽车', '新能源车', '电动车', '汽车零部件', '智能驾驶', '车载', '宁德时代', '混动', '插电混动', '增程式', '汽车整车', '智能座舱'] },
        { name: '医药', synonyms: ['创新药', '医疗器械', '中药', '疫苗', '生物制品', 'CXO', '医药商业', '医疗服务', '药店', '医药外包', '原料药', '血液制品', '减肥药', 'GLP-1', '细胞治疗', '基因治疗'] },
        { name: '军工', synonyms: ['国防', '武器', '兵器', '船舶', '航空', '航天军工', '军工电子', '军民融合', '大飞机', '国产航母'] },
        { name: '黄金', synonyms: ['贵金属'] },
        { name: '白酒', synonyms: ['酒类'] },
        { name: '锂电池', synonyms: ['锂矿', '碳酸锂', '电池', '固态电池', '电解液', '隔膜', '正极材料', '负极材料', '铜箔', '铝箔', '磷酸铁锂', '三元材料', '动力电池', '储能电池'] },
        { name: 'CPO', synonyms: ['光模块', '光连接', '硅光'] },
        { name: '零售', synonyms: ['商业百货'] },
        { name: '电力', synonyms: ['火电', '水电', '核电', '风电', '光伏', '储能', '特高压', '智能电网', '虚拟电厂', '充电桩', '电力设备', '电网', '输配电', '光伏设备', '风电设备', '核电设备', '火力发电', '水力发电', '核能', '太阳能', '新能源'] },
        { name: '并购重组', synonyms: ['重组', '借壳', '并购', '资产注入', '股权转让', '国资入股', '要约收购', '吸收合并', '分拆', '重组预案'] },
        { name: '化工', synonyms: ['化学', '化工原料', '塑料', '橡胶', '纤维', '涂料', '粘胶', '氟化工', '磷化工', '钛白粉', '维生素', '农药', '化纤'] },
        { name: '房地产', synonyms: ['地产'] },
        { name: '智能驾驶', synonyms: ['无人驾驶', '自动驾驶', '无人车', '车联网', '激光雷达', '毫米波雷达', 'HUD', '线控底盘', '车路协同'] },
        { name: '影视院线', synonyms: ['影视', '电影', '院线', '传媒', '游戏', '动漫', '短视频', '直播'] },
        { name: '小金属', synonyms: ['稀土', '钨', '钼', '锡', '锑', '锗', '镓', '铟', '钛', '锂', '钴', '镍'] },
        { name: '通信', synonyms: ['5G', '6G', '通信设备', '光通信', '物联网'] },
        { name: '一带一路', synonyms: ['基建', '建筑', '海外工程', '国际工程', '交通基建', '水利', '港口', '铁路', '公路', '桥梁', '隧道', '钢结构', '装饰', '园林', '建材', '工程机械', '工程咨询'] },
        { name: '电子元件', synonyms: ['电阻', '电容', '电感', '连接器', '继电器', '传感器'] },
        { name: '稳定币', synonyms: ['数字货币', '加密货币', '区块链', 'Web3', '跨境支付', '数字人民币', '央行数字货币', '比特币', '以太坊'] },
        { name: '脑机接口', synonyms: ['脑机', '神经接口'] },
        { name: '环保', synonyms: ['节能', '环保', '水处理', '固废处理', '大气治理', '土壤修复', '环境监测'] },
        { name: '华为概念', synonyms: ['华为', '鸿蒙', '欧拉'] },
        { name: '海峡两岸', synonyms: ['福建', '两岸', '台海'] },
        { name: '消费电子', synonyms: ['手机', '可穿戴', 'AR', 'VR'] },
        { name: '煤炭', synonyms: ['煤化工', '焦煤'] },
        { name: '农业', synonyms: ['种业', '化肥', '养殖', '饲料', '猪肉'] },
        { name: '足球概念', synonyms: ['足球'] },
        { name: '工业4.0', synonyms: ['工业互联网', '智能制造', '工业软件', '数控机床', '机器人'] },
        { name: '大消费', synonyms: ['食品', '饮料', '服装', '家电', '家居', '旅游', '酒店', '餐饮', '免税', '跨境电商', '零售'] }
    ],
    currentFilter: 'all',
    editingId: null,
    isStockListCollapsed: true,
    topicAutoFilled: false,
};

// 重构（biga-auction-arch-refactor Phase 5 彻底）：currentDate / currentGroup / currentPage /
// currentTab 已全量迁移到 app 级 useUiStore()（src/stores/uiStore.js），本文件不再持有这些
// UI 真相字段；仅保留运行期缓存 / 标记容器（_xxx 字段），符合架构规范“app-state 作运行期标记容器”。